name: PR Summary
on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write  # 允许 Danger 在 PR 上发表评论
  contents: read  # 允许读取代码文件

jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install Danger
        run: gem install danger

      - name: Run Danger
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: danger
